"""
Django settings for inland_django project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from datetime import timedelta
import datetime
from pathlib import Path

import os

from django.utils import timezone

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+v8$)h+7tme)=z$xcn_oq6*6ng#n)5^2qg+flpb#fvs-&8qz1a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["sicolog.ifreight.business", "23.224.198.22", "localhost","127.0.0.1","164.92.74.212","http://sicolog.ifreight.business/", "https://sicolog.ifreight.business/"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 'cairo',
    # 'weasyprint',

    'rest_framework',
    'rest_framework_jwt',
    'rest_framework_api_key',
    'rest_framework.authtoken',
    'corsheaders',
    'djoser',
# rest_framework_api_key
    'customer',
    'catalogos',
    'servicioVenta',
    'servicios',
    'user',
    'perfiles',
    'cotizaciones',
    'proveedores',
    'ajustesRutas',
    'usuarios',
    'administracion',
    'chatboot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # 'xframeoptions.middleware.Header',
    'django.middleware.common.BrokenLinkEmailsMiddleware',

]
AUTHENTICATION_BACKENDS = [
    # 'django.contrib.auth.backends.ModelBackend',
    'inland_django.backends.EmailAuthBackend',
]
# //agregado verificar esta linea 290621
# AUTHENTICATION_BACKENDS = (
#     'django.contrib.auth.backends.ModelBackend',
#     'apps.backend.backends.EmailAuthBackend'
# )

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
]

# CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_ALLOW_ALL = False

CORS_ORIGIN_WHITELIST = (
    'http//:localhost:8000',
)

CORS_ALLOWED_ORIGINS  = [
    "http://localhost:8080",
    "http://127.0.0.1:8000" 
]
CORS_ALLOW_ALL_ORIGINS = True


# //agregado 270521
X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'inland_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]

WSGI_APPLICATION = 'inland_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Interland',
        'USER': 'postgres',
        'PASSWORD': 'qwerty',
        'HOST': 'localhost',
        'DATABASE_PORT': '5432'
    }
}'''


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'interland',
        'USER': 'adminland',
        'PASSWORD': '4dm1nl4nd',
        'HOST': 'localhost',
        'PORT': ''
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

USE_L10N = False

DATE_FORMAT = '%m/%d/%Y'

LANGUAGE_CODE = 'es'

# TIME_ZONE = 'UTC'
TIME_ZONE='America/Mexico_City'

USE_I18N = True

USE_L10N = False

USE_TZ = True

# USE_L10N = False

DATE_FORMAT = '%m/%d/%Y'

#AGREGA DANIEL ROMERO 05/07/2023

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')




# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# //verficar esta parte ismael 270521
# X_FRAME_OPTIONS = 'SAMEORIGIN'
# X_FRAME_OPTIONS = 'DENY'

#para el envio de correos

# $pBody = $html;        
#   $transport = Swift_SmtpTransport::newInstance('smtp.office365.com', 587, 'tls')   
        #   ->setUsername('info@mx-interland.com')
        #   ->setPassword('=wAQ15&ix8');

DJANGO_SETTINGS_MODULE = 'inland_django.settings'

EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'dani_rg_iron_maiden@hotmail.com'
EMAIL_HOST_PASSWORD = 'dan1rg0m'

os.environ['DJANGO_SETTINGS_MODULE'] = 'inland_django.settings'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=20),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

JWT_AUTH = {

    'JWT_VERIFY': True,
    'JWT_VERIFY_EXPIRATION': True,
    #'JWT_EXPIRATION_DELTA': datetime.timedelta(days=1),
    'JWT_AUTH_HEADER_PREFIX': 'Bearer',
    'JWT_PAYLOAD_HANDLER': 'custom_jwt.jwt_response_payload_handler',
    'JWT_RESPONSE_PAYLOAD_HANDLER': 'custom_jwt.jwt_payload_handler',
}


