# Generated by Django 3.2 on 2023-03-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDatos',
            fields=[
                ('idEmail', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=250, null=True)),
                ('contra', models.CharField(max_length=250, null=True)),
                ('host', models.CharField(max_length=150, null=True)),
                ('port', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ('idEmail',),
            },
        ),
    ]
