# Generated by Django 3.2 on 2023-03-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildatos',
            name='usuarioAlta',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='emaildatos',
            name='usuarioModifica',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
