# Generated by Django 3.2 on 2023-03-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_auto_20230329_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildatos',
            name='dateEdita',
            field=models.DateTimeField(null=True),
        ),
    ]
