# Generated by Django 3.2 on 2023-07-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_emaildatos_dateedita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('idOferta', models.AutoField(primary_key=True, serialize=False)),
                ('oferta', models.CharField(max_length=250, null=True)),
                ('descripcion', models.CharField(max_length=250, null=True)),
                ('delDia', models.IntegerField(blank=True, default=0, null=True)),
                ('rutaImg', models.CharField(max_length=250, null=True)),
                ('inicio', models.DateTimeField(null=True)),
                ('fin', models.DateTimeField(null=True)),
                ('estatus', models.IntegerField(blank=True, default=0, null=True)),
                ('usuarioAlta', models.CharField(max_length=150, null=True)),
                ('usuarioModifica', models.CharField(max_length=150, null=True)),
                ('dateEdita', models.DateTimeField(null=True)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('idOferta',),
            },
        ),
    ]
