# Generated by Django 3.2 on 2023-07-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_ofertas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertas',
            name='nombreImg',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
