# Generated by Django 3.2 on 2024-03-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_ofertas_nombreimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='porcentajes_operacion',
            fields=[
                ('id_incremento', models.AutoField(primary_key=True, serialize=False)),
                ('mercancia', models.CharField(max_length=250, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo', models.CharField(max_length=1, null=True)),
                ('estatus', models.IntegerField(blank=True, default=0, null=True)),
                ('usuarioAlta', models.CharField(max_length=150, null=True)),
                ('usuarioModifica', models.CharField(max_length=150, null=True)),
                ('dateEdita', models.DateTimeField(null=True)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
                ('vigencia_inicio', models.DateTimeField(null=True)),
                ('vigencia_fin', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('id_incremento',),
            },
        ),
        migrations.CreateModel(
            name='rango_kilometraje',
            fields=[
                ('id_rango', models.AutoField(primary_key=True, serialize=False)),
                ('min', models.CharField(max_length=250, null=True)),
                ('max', models.CharField(max_length=250, null=True)),
                ('orden', models.IntegerField(blank=True, default=0, null=True)),
                ('estatus', models.IntegerField(blank=True, default=0, null=True)),
                ('usuarioAlta', models.CharField(max_length=150, null=True)),
                ('usuarioModifica', models.CharField(max_length=150, null=True)),
                ('dateEdita', models.DateTimeField(null=True)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id_rango',),
            },
        ),
    ]
