# Generated by Django 3.2 on 2024-11-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_porcentajes_operacion_rango_kilometraje'),
    ]

    operations = [
        migrations.CreateModel(
            name='rango_carga',
            fields=[
                ('id_rango_carga', models.AutoField(primary_key=True, serialize=False)),
                ('min', models.CharField(max_length=250, null=True)),
                ('max', models.CharField(max_length=250, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('orden', models.IntegerField(blank=True, default=0, null=True)),
                ('estatus', models.IntegerField(blank=True, default=0, null=True)),
                ('usuarioAlta', models.CharField(max_length=150, null=True)),
                ('usuarioModifica', models.CharField(max_length=150, null=True)),
                ('dateEdita', models.DateTimeField(null=True)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id_rango_carga',),
            },
        ),
        migrations.AddField(
            model_name='rango_kilometraje',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
