from django.db import models
from django.db.models.fields import IntegerField
from catalogos.models import UnitBox
from customer.models import Country,Estates, ZonasHijos

class Consecutivo(models.Model):
    numero = models.IntegerField(blank=True, null=True)
    fecha = models.DateField(null=True)
    control = models.CharField(max_length=2, blank=True, null=True)

class ServicioCotizacion(models.Model):
    tipoServicio = models.CharField(max_length=15, blank=True, null=True)
    tipoEnvio = models.CharField(max_length=15, blank=True, null=True)
    modoEnvio = models.CharField(max_length=15, blank=True, null=True)
    dateCreate = models.DateTimeField(auto_now_add=True)
    fechaCarga = models.DateField(max_length=30, blank=True, null=True)
    tipoOperacion = models.CharField(max_length=10, blank=True, null=True)
    tipoCarga = models.CharField(max_length=10, blank=True, null=True)
    tipoUnidad = models.IntegerField(blank=True, null=True)
    precioTotalInicial = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    precioTotalFinal = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    divisaInicial = models.IntegerField(blank=True, null=True, default=2)
    divisaFinal = models.IntegerField(blank=True, null=True, default=0)
    serie = models.CharField(max_length=30, blank=True, null=True)
    folio = models.IntegerField(blank=True, null=True, default=0)
    estatus = models.IntegerField(blank=True, null=True, default=0)
    usuario = models.IntegerField(blank=True, null=True, default=0)
    rechazo = models.CharField(max_length=50, blank=True, null=True)
    idVenta = models.IntegerField(blank=True, null=True, default=0)
    diasTransito = models.IntegerField(blank=True, null=True, default=0)
    estibable = models.CharField(max_length=10, blank=True, null=True, default="No")
    nametipoUnidad = models.CharField(max_length=30, blank=True, null=True)
    folioConsecutivo = models.CharField(max_length=15, blank=True, null=True)
    velocidadEnvio = models.CharField(max_length=50, blank=True, null=True)
    cambiosConsecutivo = models.IntegerField(blank=True, null=True, default=0)
    primerCambio = models.IntegerField(blank=True, null=True, default=0)
    usuarioGenera = models.CharField(max_length=150, blank=True, null=True)
    servicio_stops = models.BooleanField(max_length=7, blank=True, default=False)
    id_unidad = models.IntegerField(blank=True, null=True)

class DireccionCotizacion(models.Model):
    id = models.AutoField(primary_key=True)
    idcotizacion = models.ForeignKey(ServicioCotizacion, related_name='idCotizacion_direcciones', on_delete=models.CASCADE, null=True)
    paisOrigen = models.CharField(max_length=100, blank=True, null=True)
    idpaisOrigen = models.IntegerField(blank=True, null=True, default=0) #models.ForeignKey(Country, related_name='idpaisOrigen', on_delete=models.CASCADE, null=True)
    cpOrigen = models.CharField(max_length=10, blank=True, null=True)
    estadoOrigen = models.CharField(max_length=100, blank=True, null=True)
    idestadoOrigen = models.IntegerField(blank=True, null=True, default=0) #models.ForeignKey(Estates, related_name='idestadoOrigen', on_delete=models.CASCADE, null=True)
    ciudadOrigen = models.CharField(max_length=100, blank=True, null=True)
    coloniaOrigen = models.CharField(max_length=100, blank=True, null=True)
    calleOrigen = models.CharField(max_length=100, blank=True, null=True)
    numExtOrigen = models.CharField(max_length=100, blank=True, null=True)
    numIntOrigen = models.CharField(max_length=100, blank=True, null=True)    
    almacenOcurreOrigen = models.CharField(max_length=100, blank=True, null=True)
    paisDestino = models.CharField(max_length=100, blank=True, null=True)
    idpaisDestino =  models.IntegerField(blank=True, null=True, default=0) #models.ForeignKey(Country, related_name='idpaisDestino', on_delete=models.CASCADE, null=True)
    cpDestino = models.CharField(max_length=10, blank=True, null=True)
    estadoDestino =  models.CharField(max_length=100, blank=True, null=True)
    idestadoDestino = models.IntegerField(blank=True, null=True, default=0) #models.ForeignKey(Estates, related_name='idestadoDestino', on_delete=models.CASCADE, null=True)
    ciudadDestino = models.CharField(max_length=100, blank=True, null=True)
    coloniaDestino = models.CharField(max_length=100, blank=True, null=True)
    calleDestino = models.CharField(max_length=100, blank=True, null=True)
    numExtDestino = models.CharField(max_length=100, blank=True, null=True)
    numIntDestino = models.CharField(max_length=100, blank=True, null=True)
    almacenOcurreDestino = models.CharField(max_length=100, blank=True, null=True)
    dateCreate = models.DateTimeField(auto_now_add=True)
    usuarioGenera = models.CharField(max_length=150, blank=True, null=True)
    km = models.CharField(max_length=50, blank=True, null=True)
    zona = models.CharField(max_length=50, blank=True, null=True)
    identificador = models.CharField(max_length=200, blank=True, null=True)

class ServiciosAgregadosCotizacion(models.Model):
    idcotizacion = models.ForeignKey(ServicioCotizacion, related_name='idCotizaciones', on_delete=models.CASCADE, null=True)
    idService = models.IntegerField(blank=True, null=True)
    nameService  = models.CharField(max_length=50, blank=True, null=True)
    priceService = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    divisa = models.IntegerField(blank=True, null=True, default=2)
    dateCreate = models.DateTimeField(auto_now_add=True)
    ajusteVenta = models.BooleanField(max_length=7, blank=True, null=True)
    porcentaje = models.IntegerField(blank=True, null=True, default=0)
    agregado = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    ajusteTotal = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    idVenta = models.IntegerField(blank=True, null=True, default=0)
    subtotal = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    iva= models.IntegerField(blank=True, null=True)
    retencion= models.IntegerField(blank=True, null=True)
    total = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    porcentajeVenta = models.IntegerField(blank=True, null=True, default=0)
    porcentajeXpress = models.IntegerField(blank=True, null=True, default=0)
    porcentajeBaseOptExt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    basePorcOpt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    porcentajeIvaOpt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    monedaOptExt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    precioBaseOptExt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    totalOptExt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    porcentajeBaseExpExt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    basePorcExp = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    porcentajeIvaExp = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    monedaExpExt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    precioBaseExpExt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    totalExpExt = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    porcentajeExtra = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    #NUEVOS CAMPOS
    kilometraje = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    tarifaKilometraje = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    porcIva = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    porcZPeligrosa = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    porcNComercial = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    porcSobrepeso = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    porcSusceptible = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    aumento = models.IntegerField(blank=True, null=True)
    porcAumento = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    totalServicio = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)

class ContactoCotizacion(models.Model):
    idcotizacion = models.ForeignKey(ServicioCotizacion, related_name='idCotizacion', on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=80, blank=True, null=True)
    lada = models.IntegerField(blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    email = models.CharField(max_length=50, blank=True, null=True)
    productname = models.CharField(max_length=80, blank=True, null=True)
    description = models.CharField(max_length=80, blank=True, null=True)
    dateCreate = models.DateTimeField(auto_now_add=True)
    idVenta = models.IntegerField(blank=True, null=True, default=0)

class Rutas(models.Model):
    id_ruta = models.AutoField(primary_key=True)
    kilometraje = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    porc_zona_no_com = models.IntegerField(blank=True, null=True, default=0)
    porc_zona_pelig = models.IntegerField(blank=True, null=True, default=0)
    date_create = models.DateTimeField(auto_now_add=True)
    tiempo_estimado = models.CharField(max_length=80, blank=True, null=True)
    pais_origen = models.CharField(max_length=100, blank=True, null=True)
    estado_origen = models.CharField(max_length=100, blank=True, null=True)    
    ciudad_origen = models.CharField(max_length=100, blank=True, null=True)
    cp_origen = models.CharField(max_length=10, blank=True, null=True)
    pais_destino = models.CharField(max_length=100, blank=True, null=True)
    estado_destino =  models.CharField(max_length=100, blank=True, null=True)
    ciudad_destino = models.CharField(max_length=100, blank=True, null=True)
    cp_destino = models.CharField(max_length=10, blank=True, null=True)
    modalidad = models.CharField(max_length=3, blank=True, null=True)

class RutasFTL(models.Model):
    idRuta = models.AutoField(primary_key=True)
    kilometraje = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    porcZonaNoCom = models.IntegerField(blank=True, null=True, default=0)
    porcZonaPelig = models.IntegerField(blank=True, null=True, default=0)
    dateCreate = models.DateTimeField(auto_now_add=True)
    tiempoEstimado = models.CharField(max_length=80, blank=True, null=True)
    paisOrigen = models.CharField(max_length=100, blank=True, null=True)
    cpOrigen = models.CharField(max_length=10, blank=True, null=True)
    estadoOrigen = models.CharField(max_length=100, blank=True, null=True)    
    ciudadOrigen = models.CharField(max_length=100, blank=True, null=True)
    paisDestino = models.CharField(max_length=100, blank=True, null=True)
    cpDestino = models.CharField(max_length=10, blank=True, null=True)
    estadoDestino =  models.CharField(max_length=100, blank=True, null=True)
    ciudadDestino = models.CharField(max_length=100, blank=True, null=True)

class Tarifas(models.Model):
    idTarifa = models.AutoField(primary_key=True)
    idTarifasOrigen = models.ForeignKey(ZonasHijos, related_name='idTarifaOrigen', on_delete=models.CASCADE, null=True)
    idTarifasDestino = models.ForeignKey(ZonasHijos, related_name='idTarifaDestino', on_delete=models.CASCADE, null=True)
    tarifaKilometro = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    dateCreate = models.DateTimeField(auto_now_add=True)
    estatus = models.IntegerField(blank=True, null=True, default=0)
    tipoUnidad = models.IntegerField(blank=True, null=True, default=0)

class TarifasFTL(models.Model):
    id_Tarifa = models.AutoField(primary_key=True)
    tarifa_kilometro = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    estatus = models.IntegerField(blank=True, null=True, default=0)
    pais_origen = models.CharField(max_length=100, blank=True, null=True)
    estado_origen = models.CharField(max_length=100, blank=True, null=True)    
    ciudad_origen = models.CharField(max_length=100, blank=True, null=True)
    cp_origen = models.CharField(max_length=10, blank=True, null=True)
    pais_destino = models.CharField(max_length=100, blank=True, null=True)
    estado_destino =  models.CharField(max_length=100, blank=True, null=True)
    ciudad_destino = models.CharField(max_length=100, blank=True, null=True)
    cp_destino = models.CharField(max_length=10, blank=True, null=True)
    tipo_unidad = models.IntegerField(blank=True, null=True, default=0)
    date_create = models.DateTimeField(auto_now_add=True)

class Tarifario(models.Model):
    idTarifa = models.AutoField(primary_key=True)
    pais_origen = models.CharField(max_length=50, blank=True, null=True)
    estado_origen = models.CharField(max_length=50, blank=True, null=True)
    ciudad_origen = models.CharField(max_length=50, blank=True, null=True)
    pais_destino = models.CharField(max_length=50, blank=True, null=True)
    estado_destino = models.CharField(max_length=50, blank=True, null=True)
    ciudad_destino = models.CharField(max_length=50, blank=True, null=True)
    factor_conversion = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
    recoleccion_nissan = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
    recoleccion_tres_y_media = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
    recoleccion_rabon = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
    recoleccion_torton = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
    recoleccion_trailer = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
    flete_nacional = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
    entrega_puerto_nissan = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
    entrega_puerto_tres_y_media = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
    entrega_rabon = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
    entrega_torton = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
    entrega_trailer = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
    aplica = models.CharField(max_length=100, null=True)
    usuarioAlta = models.CharField(max_length=150, null=True)
    usuarioModifica = models.CharField(max_length=150, null=True)
    dateEdita = models.DateTimeField(null=True) 
    dateCreate = models.DateTimeField(auto_now_add=True)
    estatus = models.IntegerField(blank=True, null=True, default=0)

    class Meta:
        ordering = ('idTarifa',)

class Mercancias(models.Model):
    idMercancias = models.AutoField(primary_key=True)
    idCotizacion = models.ForeignKey(ServicioCotizacion, related_name='idCotizacion_mercancias', on_delete=models.CASCADE, null=True)
    embalaje = models.CharField(max_length=50, blank=True, null=True)
    cantidad = models.IntegerField(blank=True, null=True, default=0)
    factor_conversion = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
    largo = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
    ancho = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
    alto = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
    volumen = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
    volumenTotal = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
    pesoVolumetrico = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
    pesoVolumetricoTotal = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
    peso = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
    pesoTotal = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
    estibable = models.CharField(max_length=150, null=True)
    upeso = models.CharField(max_length=10, null=True)
    umedi = models.CharField(max_length=10, null=True)
    precioVolumen = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
    usuarioModifica = models.CharField(max_length=150, null=True)
    usuarioAlta = models.CharField(max_length=150, null=True)
    dateEdita = models.DateTimeField(null=True) 
    dateCreate = models.DateTimeField(auto_now_add=True)
    mercancia = models.CharField(max_length=50, blank=True, null=True)
    un = models.CharField(max_length=50, blank=True, null=True)
    classP = models.CharField(max_length=50, blank=True, null=True)
    grados = models.CharField(max_length=50, blank=True, null=True)
    descripRef = models.CharField(max_length=50, blank=True, null=True)
    ruta = models.CharField(max_length=200, blank=True, null=True)
    es_peligrosa = models.BooleanField(max_length=7, blank=True, default=False)
    es_refrigerada = models.BooleanField(max_length=7, blank=True, default=False)
    idclasificacion = models.IntegerField(blank=True, null=True)
    descripcion_mercancia = models.CharField(max_length=200, blank=True, null=True)
    orden = models.IntegerField(blank=True, null=True)
    clasificacion = models.CharField(max_length=200, blank=True, null=True)
    
class Planes(models.Model):
    idPlan = models.AutoField(primary_key=True)
    orden = models.IntegerField(blank=True, null=True)
    idCotizacion = models.ForeignKey(ServicioCotizacion, related_name='idCotizacion_planes', on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=50, blank=True, null=True)
    icon = models.CharField(max_length=50, blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
    services = models.CharField(max_length=250, blank=True, null=True)
    bandwidth = models.CharField(max_length=250, blank=True, null=True)
    domain = models.CharField(max_length=250, blank=True, null=True)
    user = models.CharField(max_length=250, blank=True, null=True)
    seleccionado = models.IntegerField(blank=True, null=True)
    ribbon = models.CharField(max_length=20, blank=True, null=True)
