# Generated by Django 3.2 on 2021-06-08 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('estatus', models.IntegerField()),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=60)),
                ('lada', models.CharField(max_length=6, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('estatus', models.IntegerField()),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('estatus', models.IntegerField()),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('lada', models.CharField(blank=True, max_length=6, null=True)),
                ('pais', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
                ('cp', models.CharField(blank=True, max_length=10, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('colonia', models.CharField(blank=True, max_length=50, null=True)),
                ('calle', models.TextField(blank=True, null=True)),
                ('noInterior', models.CharField(blank=True, max_length=20, null=True)),
                ('noExterior', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=200)),
                ('tipoEmpresa', models.CharField(blank=True, max_length=20, null=True)),
                ('rfc', models.CharField(max_length=13, null=True)),
                ('textId', models.CharField(blank=True, max_length=30, null=True)),
                ('usoCfdi', models.CharField(blank=True, max_length=30, null=True)),
                ('formaPago', models.CharField(blank=True, max_length=30, null=True)),
                ('metodoPago', models.CharField(blank=True, max_length=30, null=True)),
                ('estatus', models.CharField(max_length=200)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DataComplementary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbersemployes', models.CharField(blank=True, max_length=200, null=True)),
                ('business', models.CharField(blank=True, max_length=200, null=True)),
                ('specification', models.CharField(blank=True, max_length=100, null=True)),
                ('conditions', models.CharField(blank=True, max_length=100, null=True)),
                ('paydaysweeks', models.CharField(blank=True, max_length=100, null=True)),
                ('generalnotesweeks', models.CharField(blank=True, max_length=100, null=True)),
                ('paydaysdate', models.CharField(blank=True, max_length=100, null=True)),
                ('generalnotesdate', models.CharField(blank=True, max_length=100, null=True)),
                ('creditdays', models.CharField(blank=True, max_length=100, null=True)),
                ('credit', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.CharField(default=0, max_length=200)),
            ],
            options={
                'ordering': ('business',),
            },
        ),
        migrations.CreateModel(
            name='Estates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('estatus', models.IntegerField()),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estates', to='customer.country')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('estatus', models.IntegerField()),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Lada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('alias', models.CharField(max_length=5)),
                ('code', models.CharField(max_length=6)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('estatus', models.IntegerField()),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TipoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('estatus', models.IntegerField()),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UsoCfdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('estatus', models.IntegerField()),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='ZipCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_postal', models.CharField(max_length=20, null=True)),
                ('asentamiento', models.CharField(max_length=200, null=True)),
                ('colonia', models.CharField(max_length=200, null=True)),
                ('municipio', models.CharField(max_length=200, null=True)),
                ('estado_n', models.CharField(max_length=200, null=True)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado', to='customer.estates')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais', to='customer.country')),
            ],
            options={
                'ordering': ('codigo_postal',),
            },
        ),
        migrations.CreateModel(
            name='RutasCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.IntegerField()),
                ('cpOrigen', models.CharField(max_length=20)),
                ('ciudadOrigen', models.CharField(max_length=200)),
                ('cpDestino', models.CharField(max_length=20)),
                ('ciudadDestino', models.CharField(max_length=200)),
                ('estatus', models.IntegerField()),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
                ('estadoDestino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estadoDestino_id', to='customer.estates')),
                ('estadoOrigen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estadoOrigen_id', to='customer.estates')),
                ('paisDestino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paisDestino_id', to='customer.country')),
                ('paisOrigen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paisOrigen_id', to='customer.country')),
            ],
            options={
                'ordering': ('paisOrigen',),
            },
        ),
        migrations.CreateModel(
            name='FilesCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('ruta', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('statuspdf', models.IntegerField(blank=True, null=True)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customer.customer')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
