# Generated by Django 3.2 on 2021-06-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filescustomer',
            name='ruta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
