# Generated by Django 3.2 on 2021-06-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_filescustomer_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filescustomer',
            name='ruta',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
