# Generated by Django 3.2 on 2021-06-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_filescustomer_ruta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('nombre',)},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='nombre',
        ),
    ]
