# Generated by Django 3.2 on 2021-06-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210614_0835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='nombre',
            new_name='name',
        ),
    ]
