# Generated by Django 3.2 on 2023-01-24 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_datacomplementary_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('idZona', models.IntegerField(primary_key=True, serialize=False)),
                ('clasificacion', models.CharField(max_length=100, null=True)),
                ('claveIde', models.CharField(max_length=1, null=True)),
                ('identificador', models.CharField(max_length=200, null=True)),
                ('estado_n', models.CharField(max_length=200, null=True)),
                ('municipio', models.CharField(max_length=200, null=True)),
                ('vigencia', models.DateTimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_zonas', to='customer.estates')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais_zonas', to='customer.country')),
            ],
            options={
                'ordering': ('idZona',),
            },
        ),
    ]
