# Generated by Django 3.2 on 2023-01-24 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_zonas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonasHijos',
            fields=[
                ('idZonasHijo', models.IntegerField(primary_key=True, serialize=False)),
                ('codigoPostal', models.CharField(max_length=15, null=True)),
                ('colonia', models.CharField(max_length=50, null=True)),
                ('idZonas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idZona_zona', to='customer.zonas')),
            ],
            options={
                'ordering': ('idZonasHijo',),
            },
        ),
    ]
