# Generated by Django 3.2 on 2023-01-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_zonashijos'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonas',
            name='estatus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
