# Generated by Django 3.2 on 2023-01-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_zonas_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonashijos',
            name='idZonasHijo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
