# Generated by Django 3.2 on 2023-01-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_zonashijos_idzonashijo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonas',
            name='idZona',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
