# Generated by Django 3.2 on 2023-01-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_zonas_idzona'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonas',
            name='llave',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
