# Generated by Django 3.2 on 2023-01-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_zonas_llave'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonashijos',
            name='municipio',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
