# Generated by Django 3.2 on 2023-03-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_zonashijos_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonashijos',
            name='colonia',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
