# Generated by Django 3.2 on 2023-05-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_zonashijos_colonia'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipcodes',
            name='direccion',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
