# Generated by Django 3.2 on 2023-05-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_zipcodes_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='datosAyuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDatoAyuda', models.IntegerField()),
                ('direccion', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
