# Generated by Django 3.2 on 2023-05-24 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_datosayuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosayuda',
            name='idDatoAyuda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idAyuda_zip', to='customer.zipcodes'),
        ),
    ]
