# Generated by Django 3.2 on 2023-09-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_alter_datosayuda_iddatoayuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcodes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
