# Generated by Django 3.2 on 2024-07-17 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_alter_zipcodes_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Select_Zonas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_postal', models.CharField(max_length=20, null=True)),
                ('asentamiento', models.CharField(max_length=200, null=True)),
                ('colonia', models.CharField(max_length=200, null=True)),
                ('municipio', models.CharField(max_length=200, null=True)),
                ('estado_n', models.CharField(max_length=200, null=True)),
                ('pais_n', models.CharField(max_length=200, null=True)),
                ('direccion', models.CharField(max_length=250, null=True)),
                ('check_zona_c', models.BooleanField(blank=True, default=False)),
                ('check_zona_nc', models.BooleanField(blank=True, default=False)),
                ('check_zona_p', models.BooleanField(blank=True, default=False)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_select', to='customer.estates')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais_select', to='customer.country')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
