# Generated by Django 3.2 on 2021-06-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitbox',
            name='code_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
