# Generated by Django 3.2 on 2021-06-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_alter_unitbox_code_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(blank=True, max_length=100, null=True)),
                ('destino', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'ordering': ('pais',),
            },
        ),
    ]
