# Generated by Django 3.2.3 on 2021-08-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_customs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaveProdServ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_prodserv', models.IntegerField(blank=True, default=0, max_length=15, null=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('fechaInicioVigencia', models.DateField(blank=True, default=0, null=True)),
                ('fechaFinVigencia', models.DateField(blank=True, default=0, null=True)),
                ('ivaTraslado', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('iepsTraslado', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('complementoIncluir', models.CharField(blank=True, default='', max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaveUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claveUnidad', models.IntegerField(blank=True, default=0, max_length=15, null=True)),
                ('nombre', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('nota', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('fechaInicioVigencia', models.DateField(blank=True, default=0, null=True)),
                ('fechaFinVigencia', models.DateField(blank=True, default=0, null=True)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
                ('simbolo', models.CharField(blank=True, default=True, max_length=40)),
            ],
        ),
    ]
