# Generated by Django 3.2.3 on 2021-08-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_claveprodserv_claveunidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claveProductoServicio', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='claveprodserv',
            name='clave_prodserv',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='claveunidad',
            name='claveUnidad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
