# Generated by Django 3.2.3 on 2021-08-13 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_datacomplementary_customer'),
        ('catalogos', '0005_auto_20210813_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claveProductoServicio', models.IntegerField(blank=True, default=0, null=True)),
                ('nombreProductoServicios', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('unidad', models.IntegerField(blank=True, default=0, null=True)),
                ('numeroIdentificacion', models.IntegerField(blank=True, default=True, null=True)),
                ('estadoVentas', models.BooleanField(blank=True, default=False, null=True)),
                ('estadoCompras', models.BooleanField(blank=True, default=False, null=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='codigoAduanero',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='divisaCompra',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='divisaVenta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='estadoCompras',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='estadoVentas',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='idPaisOrigen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idpays', to='customer.country'),
        ),
        migrations.AddField(
            model_name='producto',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='longitudName',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='naturaleza',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombreProductoServicios',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nota',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='numeroIdentificacion',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='paisOrigen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='pesoName',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precioVenta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precioVentaMin',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precioVentaName',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='superficie',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='superficieName',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tasaDivisaCompra',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tasaIvaVenta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tasaRetencionCompra',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tasaRetencionVenta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='volumen',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='volumenName',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
    ]
