# Generated by Django 3.2.3 on 2021-08-13 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_auto_20210813_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='dateCreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
