# Generated by Django 3.2.3 on 2021-08-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_producto_datecreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='claveUnidad',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='claveprodserv',
            name='clave_prodserv',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='claveunidad',
            name='claveUnidad',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='claveProductoServicio',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreProductoServicios',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='claveProductoServicio',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
