# Generated by Django 3.2.3 on 2021-08-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_auto_20210813_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='naturaleza',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
