# Generated by Django 3.2.3 on 2021-08-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0009_alter_producto_naturaleza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idPaisOrigen',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
