# Generated by Django 3.2.3 on 2021-08-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0010_alter_producto_idpaisorigen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estatus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
