# Generated by Django 3.2.3 on 2021-08-13 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0011_producto_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='claveUnidad',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='dateCreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='dia',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='divisaCompra',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='divisaVenta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='estatus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='hora',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='idPaisOrigen',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='mes',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='nota',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='paisOrigen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precioVenta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precioVentaMin',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precioVentaName',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='semana',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tasaDivisaCompra',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tasaIvaVenta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tasaRetencionCompra',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tasaRetencionVenta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='year',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
