# Generated by Django 3.2.3 on 2021-08-13 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0012_auto_20210813_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='dia',
            new_name='tiempo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='semana',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='year',
        ),
    ]
