# Generated by Django 3.2.3 on 2021-08-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0013_auto_20210813_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='codigoAduanero',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
