# Generated by Django 3.2.3 on 2021-08-16 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0014_servicio_codigoaduanero'),
    ]

    operations = [
        migrations.AddField(
            model_name='claveprodserv',
            name='dateCreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
