# Generated by Django 3.2.3 on 2021-08-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0015_claveprodserv_datecreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='claveprodserv',
            name='estatus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
