# Generated by Django 3.2.3 on 2021-08-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0016_claveprodserv_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='claveunidad',
            name='estatus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
