# Generated by Django 3.2.3 on 2021-08-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0018_alter_claveunidad_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claveunidad',
            name='nota',
            field=models.CharField(blank=True, default='', max_length=420, null=True),
        ),
    ]
