# Generated by Django 3.2.3 on 2021-08-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0019_alter_claveunidad_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='claveUnidad',
            field=models.CharField(blank=True, default=0, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='claveUnidad',
            field=models.CharField(blank=True, default=0, max_length=300, null=True),
        ),
    ]
