# Generated by Django 3.2.3 on 2021-08-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0020_auto_20210817_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='claveProductoServicio',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreProductoServicios',
            field=models.CharField(blank=True, default=0, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='claveProductoServicio',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombreProductoServicios',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
