# Generated by Django 3.2.3 on 2021-08-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0023_auto_20210818_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
