# Generated by Django 3.2.3 on 2021-08-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0025_puesto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
