# Generated by Django 3.2.3 on 2021-08-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0026_puesto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('apellidos', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
