# Generated by Django 3.2 on 2023-01-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0028_rename_acceso_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitbox',
            name='mostrarLista',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
