# Generated by Django 3.2 on 2023-03-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0030_modulos_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisos',
            name='agregar',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='permisos',
            name='editar',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='permisos',
            name='eliminar',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='permisos',
            name='lectura',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
