# Generated by Django 3.2 on 2023-03-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0031_auto_20230316_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulos',
            name='icon',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='modulos',
            name='idMenu',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='modulos',
            name='isSubmenu',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='modulos',
            name='link',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
