# Generated by Django 3.2 on 2023-03-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0032_auto_20230322_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulos',
            name='usuario',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
