# Generated by Django 3.2 on 2023-04-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0035_claveprodserv_susceptiblerobo'),
    ]

    operations = [
        migrations.AddField(
            model_name='claveprodserv',
            name='porcentajeRobo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
