# Generated by Django 3.2 on 2023-04-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0036_claveprodserv_porcentajerobo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embalaje',
            fields=[
                ('idEmabalaje', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('estatus', models.IntegerField(blank=True, default=0, null=True)),
                ('largo', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('alto', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('cantidadMaxima', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
