# Generated by Django 3.2 on 2023-04-25 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0037_embalaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='embalaje',
            old_name='idEmabalaje',
            new_name='idEmbalaje',
        ),
    ]
