# Generated by Django 3.2 on 2023-05-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0039_embalaje_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='claveprodserv',
            name='materialPeligroso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='claveprodserv',
            name='palabrasSimilares',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='claveprodserv',
            name='sectorIndustrial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='claveprodserv',
            name='tipoMercancia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
