# Generated by Django 3.2 on 2023-05-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0040_auto_20230530_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claveprodserv',
            name='palabrasSimilares',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
