# Generated by Django 3.2 on 2023-05-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0041_alter_claveprodserv_palabrassimilares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claveprodserv',
            name='palabrasSimilares',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
