# Generated by Django 3.2 on 2023-05-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0042_alter_claveprodserv_palabrassimilares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claveprodserv',
            name='palabrasSimilares',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
