# Generated by Django 3.2 on 2023-05-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0044_alter_claveprodserv_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitbox',
            name='capacidadMaxima',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
