# Generated by Django 3.2 on 2023-06-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0045_unitbox_capacidadmaxima'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitbox',
            name='imagen',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
