# Generated by Django 3.2 on 2023-08-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0047_terminos_condiciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminos_condiciones',
            old_name='codicion',
            new_name='condicion',
        ),
    ]
