# Generated by Django 3.2 on 2023-08-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0048_rename_codicion_terminos_condiciones_condicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geocercas',
            fields=[
                ('idGeocerca', models.AutoField(primary_key=True, serialize=False)),
                ('codigoPostal', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('lat', models.IntegerField(blank=True, default=0, null=True)),
                ('lng', models.CharField(blank=True, default='', max_length=90, null=True)),
                ('orden', models.IntegerField(blank=True, default=0, null=True)),
                ('estatus', models.IntegerField(blank=True, default=0, null=True)),
                ('usuarioAlta', models.CharField(blank=True, max_length=120, null=True)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
                ('usuarioModifica', models.CharField(max_length=150, null=True)),
                ('dateEdita', models.DateTimeField(null=True)),
            ],
        ),
    ]
