# Generated by Django 3.2 on 2023-08-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0049_geocercas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocercas',
            name='codigoPostal',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='geocercas',
            name='lat',
            field=models.CharField(blank=True, default='', max_length=90, null=True),
        ),
    ]
