# Generated by Django 3.2 on 2023-08-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0050_auto_20230809_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocercas',
            name='poligono',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
