# Generated by Django 3.2 on 2023-08-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0051_geocercas_poligono'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocercas',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
