# Generated by Django 3.2 on 2023-08-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0052_geocercas_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocercas',
            name='lat_centro',
            field=models.CharField(blank=True, default='', max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='geocercas',
            name='lng_centro',
            field=models.CharField(blank=True, default='', max_length=90, null=True),
        ),
    ]
