# Generated by Django 3.2 on 2023-08-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0053_auto_20230810_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocercas',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='geocercas',
            name='pais',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
