# Generated by Django 3.2 on 2023-10-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0054_auto_20230814_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='forma_pago',
            fields=[
                ('id_forma_pago', models.AutoField(primary_key=True, serialize=False)),
                ('clave_forma_pago', models.CharField(blank=True, default='', max_length=3, null=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('descripcion_completa', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('estatus', models.IntegerField(blank=True, default=0, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_edita', models.DateTimeField(null=True)),
                ('usuario_alta', models.CharField(blank=True, max_length=120, null=True)),
                ('usuario_modifica', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='metodo_pago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('clave_metodo_pago', models.CharField(blank=True, default='', max_length=3, null=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('descripcion_completa', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('estatus', models.IntegerField(blank=True, default=0, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_edita', models.DateTimeField(null=True)),
                ('usuario_alta', models.CharField(blank=True, max_length=120, null=True)),
                ('usuario_modifica', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='regimen_fiscal',
            fields=[
                ('id_regimen_fiscal', models.AutoField(primary_key=True, serialize=False)),
                ('clave_regimen_fiscal', models.IntegerField(blank=True, default=0, null=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('descripcion_completa', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('estatus', models.IntegerField(blank=True, default=0, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_edita', models.DateTimeField(null=True)),
                ('usuario_alta', models.CharField(blank=True, max_length=120, null=True)),
                ('usuario_modifica', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_empresa',
            fields=[
                ('id_tipo_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('estatus', models.IntegerField(blank=True, default=0, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_edita', models.DateTimeField(null=True)),
                ('usuario_alta', models.CharField(blank=True, max_length=120, null=True)),
                ('usuario_modifica', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_persona',
            fields=[
                ('id_tipo_persona', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('estatus', models.IntegerField(blank=True, default=0, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_edita', models.DateTimeField(null=True)),
                ('usuario_alta', models.CharField(blank=True, max_length=120, null=True)),
                ('usuario_modifica', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
