# Generated by Django 3.2 on 2023-10-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0055_forma_pago_metodo_pago_regimen_fiscal_tipo_empresa_tipo_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_cliente',
            fields=[
                ('id_tipo_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('estatus', models.IntegerField(blank=True, default=0, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_edita', models.DateTimeField(null=True)),
                ('usuario_alta', models.CharField(blank=True, max_length=120, null=True)),
                ('usuario_modifica', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
