# Generated by Django 3.2 on 2024-03-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0056_tipo_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zonas_Tarifas',
            fields=[
                ('id_zona_tarifa', models.AutoField(primary_key=True, serialize=False)),
                ('clasificacion', models.IntegerField(blank=True, default=0, null=True)),
                ('pais_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('cp_origen', models.CharField(blank=True, max_length=10, null=True)),
                ('pais_destino', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_destino', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad_destino', models.CharField(blank=True, max_length=100, null=True)),
                ('cp_destino', models.CharField(blank=True, max_length=10, null=True)),
                ('estatus', models.IntegerField(blank=True, default=0, null=True)),
                ('km', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('estatus_geocerca', models.IntegerField(blank=True, default=0, null=True)),
                ('usuario_alta', models.CharField(max_length=150, null=True)),
                ('usuario_modifica', models.CharField(max_length=150, null=True)),
                ('date_edita', models.DateTimeField(null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='geocercas',
            name='estatus_geocerca',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='geocercas',
            name='kilometros_redonda',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='geocercas',
            name='nombre_corto',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='geocercas',
            name='porcentaje_incremento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unitbox',
            name='precio_kilometraje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
