# Generated by Django 3.2 on 2024-11-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0058_geocercas_colonia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitbox',
            old_name='peso_bruto_carga',
            new_name='estadia_dia',
        ),
        migrations.RemoveField(
            model_name='unitbox',
            name='orderg',
        ),
        migrations.AddField(
            model_name='geocercas',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='geocercas',
            name='idestado',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='geocercas',
            name='idpais',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='unitbox',
            name='aplica_estiba',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='unitbox',
            name='horas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unitbox',
            name='maniobras',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unitbox',
            name='servicio_aplica',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
