# Generated by Django 3.2 on 2024-11-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0059_auto_20241105_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitbox',
            name='orderg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='unitbox',
            name='peso_bruto_carga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
