# Generated by Django 3.2 on 2024-11-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0061_remove_geocercas_idestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocercas',
            name='idestado',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
