# Generated by Django 3.2 on 2024-03-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios_chatboot',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250, null=True)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('primera_vez', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ('id_usuario',),
            },
        ),
    ]
