# Generated by Django 3.2 on 2024-10-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatboot', '0005_auto_20240905_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='seguimiento_lead_to_agente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_agente', models.IntegerField(blank=True, default=0, null=True)),
                ('nombre_agente', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_agente', models.CharField(blank=True, max_length=50, null=True)),
                ('servicio', models.IntegerField(blank=True, default=0, null=True)),
                ('nombre_lead', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_lead', models.CharField(blank=True, max_length=100, null=True)),
                ('date_create', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
