# Generated by Django 3.2 on 2024-10-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatboot', '0006_seguimiento_lead_to_agente'),
    ]

    operations = [
        migrations.CreateModel(
            name='leads_to_agentes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_agente', models.IntegerField(blank=True, default=0, null=True)),
                ('nombre_agente', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_agente', models.CharField(blank=True, max_length=16, null=True)),
                ('apellido_agente', models.CharField(blank=True, max_length=50, null=True)),
                ('servicio', models.IntegerField(blank=True, default=0, null=True)),
                ('nombre_lead', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_lead', models.CharField(blank=True, max_length=100, null=True)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('agente_index', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='seguimiento_lead_to_agente',
        ),
    ]
