# Generated by Django 3.2 on 2024-11-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatboot', '0009_auto_20241104_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='leds_chatboot',
            name='correo_usr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
