# Generated by Django 3.2 on 2025-03-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatboot', '0011_leds_chatboot_tipo_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leds_chatboot',
            name='mensaje_boot',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
