# Generated by Django 3.2 on 2021-06-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeproduct', models.CharField(blank=True, max_length=20, null=True)),
                ('nameproduct', models.CharField(blank=True, max_length=30, null=True)),
                ('unit', models.CharField(blank=True, max_length=15, null=True)),
                ('codeunit', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
