# Generated by Django 3.2 on 2023-01-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
