# Generated by Django 3.2 on 2024-11-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_services_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='aplica',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='precioServ',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='codeproduct',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='nameproduct',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
