# Generated by Django 3.2 on 2021-06-22 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoOperacion', models.IntegerField()),
                ('tipoServicio', models.IntegerField()),
                ('servicio', models.CharField(blank=True, max_length=100, null=True)),
                ('idServicio', models.IntegerField(blank=True, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('iva', models.IntegerField(blank=True, null=True)),
                ('retencion', models.IntegerField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('divisa', models.IntegerField(blank=True, null=True)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
                ('dateFin', models.DateTimeField(blank=True, null=True)),
                ('diasTransito', models.IntegerField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('userCreate', models.IntegerField(blank=True, null=True)),
                ('paisOrigen', models.CharField(blank=True, max_length=100, null=True)),
                ('cpOrigen', models.CharField(blank=True, max_length=10, null=True)),
                ('estadoOrigen', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudadOrigen', models.CharField(blank=True, max_length=100, null=True)),
                ('paisDestino', models.CharField(blank=True, max_length=100, null=True)),
                ('cpDestino', models.CharField(blank=True, max_length=10, null=True)),
                ('estadoDestino', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudadDestino', models.CharField(blank=True, max_length=100, null=True)),
                ('idAduana', models.IntegerField(blank=True, default=0, null=True)),
                ('estatusCompleto', models.IntegerField(blank=True, default=0, null=True)),
                ('unidaModality', models.CharField(blank=True, max_length=5, null=True)),
                ('unHazmat', models.CharField(blank=True, max_length=50, null=True)),
                ('classHazmat', models.CharField(blank=True, max_length=50, null=True)),
                ('idCotizacion', models.IntegerField(blank=True, default=0, null=True)),
                ('banCOntesto', models.IntegerField(blank=True, default=0, null=True)),
                ('valorMercancia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fechaPricing', models.DateTimeField(blank=True, null=True)),
                ('tipoUnidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidad', to='catalogos.unitbox')),
            ],
            options={
                'ordering': ('servicio',),
            },
        ),
    ]
