# Generated by Django 3.2 on 2021-06-22 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_datacomplementary_customer'),
        ('servicioVenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioventa',
            name='idestadoDestino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicioventa',
            name='idestadoOrigen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estadoOrigenid', to='customer.estates'),
        ),
        migrations.AddField(
            model_name='servicioventa',
            name='idpaisDestino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paisDestinoid', to='customer.country'),
        ),
        migrations.AddField(
            model_name='servicioventa',
            name='idpaisOrigen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paisOrigenid', to='customer.country'),
        ),
        migrations.AlterField(
            model_name='servicioventa',
            name='estadoDestino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estadoDestinoid', to='customer.estates'),
        ),
    ]
