# Generated by Django 3.2 on 2021-06-22 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_datacomplementary_customer'),
        ('servicioVenta', '0002_auto_20210622_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioventa',
            name='dateFin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicioventa',
            name='estadoDestino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicioventa',
            name='idestadoDestino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estadoDestinoid', to='customer.estates'),
        ),
    ]
