# Generated by Django 3.2 on 2021-06-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicioVenta', '0003_auto_20210622_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioventa',
            name='dateInicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
