# Generated by Django 3.2 on 2021-06-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicioVenta', '0005_servicioventa_modality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioventa',
            name='tipoOperacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicioventa',
            name='tipoServicio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
