# Generated by Django 3.2.3 on 2021-07-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicioVenta', '0006_auto_20210629_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioventa',
            name='checkVentas',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='servicioventa',
            name='porcentajeTotal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='servicioventa',
            name='porcentajeVenta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='servicioventa',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
