# Generated by Django 3.2.3 on 2021-07-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicioVenta', '0007_auto_20210712_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioventa',
            name='idProovedor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
