# Generated by Django 3.2.3 on 2021-07-12 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicioVenta', '0008_servicioventa_idproovedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicioventa',
            old_name='porcentajeTotal',
            new_name='porcentajeXpress',
        ),
    ]
