# Generated by Django 3.2.3 on 2021-07-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicioVenta', '0010_rename_idproovedor_servicioventa_idproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioventa',
            name='velocidadEnvio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
