# Generated by Django 3.2.3 on 2021-07-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicioVenta', '0011_servicioventa_velocidadenvio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioventa',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
