# Generated by Django 3.2.3 on 2021-08-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicioVenta', '0012_alter_servicioventa_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioventa',
            name='ruta',
            field=models.CharField(blank=True, default='sin ruta', max_length=15, null=True),
        ),
    ]
