# Generated by Django 3.2.3 on 2021-08-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicioVenta', '0013_servicioventa_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioventa',
            name='classHazmat',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicioventa',
            name='unHazmat',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
