# Generated by Django 3.2 on 2023-01-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicioVenta', '0014_auto_20210810_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioventa',
            name='zona',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
