from django.db import models
from django.db.models.base import Model

class Usuarios(models.Model):
    apellidos = models.CharField(max_length=40, blank=True, null=True, default="")
    nombre = models.CharField(max_length=40, blank=True, null=True, default="")
    puesto_funcion = models.CharField(max_length=40, blank=True, null=True, default="")
    login = models.CharField(max_length=40, blank=True, null=True, default="")
    password = models.CharField(max_length=40, blank=True, null=True, default="")
    administrador = models.BooleanField(blank=True, null=True, default=False)
    # tipo = models.CharField(max_length=40, blank=True, null=True, default="")
    telefonoJob = models.CharField(max_length=40, blank=True, default="")
    movil = models.CharField(max_length=40,  null=True, default="")
    # fax = models.CharField(max_length=40, blank=True, null=True, default="")
    email = models.CharField(max_length=40, blank=True, null=True, default="")
    # firma = models.CharField(max_length=40, blank=True, null=True, default="")
    responsable = models.CharField(max_length=40, blank=True, null=True, default="")
    nota = models.CharField(max_length=40, blank=True, null=True, default="")
    accesos = models.CharField(max_length=40, blank=True, null=True, default="")
    # privilegios = models.CharField(max_length=40, blank=True, null=True, default="")
    # licencia = models.CharField(max_length=40, blank=True, null=True, default="")
    # seguro_social = models.CharField(max_length=40, blank=True, null=True, default="")
    # dateInicioActividades = models.DateField(blank=True, null=True, default=0)
    sucursal = models.CharField(max_length=40, blank=True, null=True, default="")
    perfil = models.CharField(max_length=40, blank=True, null=True, default="")
    dateCreate = models.DateTimeField(auto_now_add=True)
    estatus = models.IntegerField(blank=True, null=True)
    last_login = models.DateTimeField(max_length=30, blank=True, null=True)
    terminos_condiciones=models.BooleanField(blank=True, null=True, default=False)
    urlImg = models.CharField(max_length=250,  null=True, default="")
    nombreImg = models.CharField(max_length=250,  null=True, default="")

    tipo_cliente = models.IntegerField(blank=True, null=True)
    tipo_persona = models.IntegerField(blank=True, null=True)
    nombre_empresa = models.CharField(max_length=250,  null=True, default="")
    tipo_empresa = models.CharField(max_length=250,  null=True, default="")
    rfc = models.CharField(max_length=20,  null=True, default="")
    regimen_fiscal = models.IntegerField(blank=True, null=True)
    metodo_pago = models.IntegerField(blank=True, null=True)
    forma_pago = models.IntegerField(blank=True, null=True)
    pais_fiscal = models.IntegerField(blank=True, null=True)
    estado_fiscal = models.CharField(max_length=250,  null=True, default="")
    ciudad_fiscal = models.CharField(max_length=250,  null=True, default="")
    cp_fiscal = models.CharField(max_length=10,  null=True, default="")
    calle_fiscal = models.CharField(max_length=250,  null=True, default="")
    numero_exterior_fiscal = models.CharField(max_length=20,  null=True, default="")
    numero_interior_fiscal = models.CharField(max_length=20,  null=True, default="")
    estado_cuenta = models.CharField(max_length=250,  null=True, default="")
    comprobante_domicilio_fiscal = models.CharField(max_length=250,  null=True, default="")