# Generated by Django 3.2.3 on 2021-08-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('nombre', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('puesto_funcion', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('login', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('administrador', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('tipo', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('telefonoJob', models.IntegerField(blank=True, default='', null=True)),
                ('movil', models.IntegerField(blank=True, default='', null=True)),
                ('fax', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('firma', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('responsable', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('nota', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('accesos', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('privilegios', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('licencia', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('seguro_social', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('dateInicioActividades', models.DateField(blank=True, default=0, null=True)),
                ('sucursal', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('perfil', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
