# Generated by Django 3.2.3 on 2021-08-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_user_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='administrador',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
