# Generated by Django 3.2.3 on 2021-08-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuarios_administrador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='dateInicioActividades',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='licencia',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='privilegios',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='seguro_social',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='tipo',
        ),
    ]
