# Generated by Django 3.2 on 2023-03-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20210819_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='movil',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefonoJob',
            field=models.CharField(default='', max_length=40, null=True),
        ),
    ]
