# Generated by Django 3.2 on 2023-03-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20230310_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='telefonoJob',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
