# Generated by Django 3.2 on 2023-07-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuarios_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='terminos_condiciones',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
