# Generated by Django 3.2 on 2023-07-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_usuarios_terminos_condiciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='urlImg',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
