# Generated by Django 3.2 on 2023-07-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_usuarios_urlimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='nombreImg',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
