# Generated by Django 3.2 on 2023-10-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_usuarios_nombreimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='calle_fiscal',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='ciudad_fiscal',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='comprobante_domicilio_fiscal',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='cp_fiscal',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='estado_cuenta',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='estado_fiscal',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='forma_pago',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='metodo_pago',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='nombre_empresa',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='numero_exterior_fiscal',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='numero_interior_fiscal',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='pais_fiscal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='regimen_fiscal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='rfc',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='tipo_cliente',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='tipo_empresa',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='tipo_persona',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
