# Generated by Django 3.2.3 on 2021-08-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(blank=True, max_length=100, null=True)),
                ('destino', models.CharField(blank=True, max_length=100, null=True)),
                ('tipoUnidad', models.CharField(blank=True, max_length=100, null=True)),
                ('nombeTipoUnidad', models.CharField(blank=True, max_length=100, null=True)),
                ('tipoMercancia', models.CharField(blank=True, max_length=100, null=True)),
                ('tipoEnvio', models.CharField(blank=True, max_length=100, null=True)),
                ('precioKilometros', models.IntegerField(blank=True, null=True)),
                ('divisa', models.IntegerField(blank=True, null=True)),
                ('estatus', models.IntegerField(blank=True, null=True)),
                ('idUsuario', models.IntegerField(blank=True, null=True)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
