# Generated by Django 3.2.3 on 2021-08-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustesRutas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutas',
            name='idUsuario',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
