# Generated by Django 3.2.3 on 2021-08-09 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajustesRutas', '0002_alter_rutas_idusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutas',
            name='nombeTipoUnidad',
        ),
    ]
