# Generated by Django 3.2.3 on 2021-07-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciosagregadoscotizacion',
            name='ajusteTotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serviciosagregadoscotizacion',
            name='ajusteVenta',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='serviciosagregadoscotizacion',
            name='porcentaje',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
