# Generated by Django 3.2.3 on 2021-07-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_auto_20210705_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciosagregadoscotizacion',
            name='agregado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
