# Generated by Django 3.2.3 on 2021-07-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_serviciosagregadoscotizacion_agregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciosagregadoscotizacion',
            name='ajusteVenta',
            field=models.BooleanField(blank=True, max_length=7, null=True),
        ),
    ]
