# Generated by Django 3.2.3 on 2021-07-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_alter_serviciosagregadoscotizacion_ajusteventa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviciocotizacion',
            old_name='precioTotal',
            new_name='precioTotalFinal',
        ),
        migrations.AddField(
            model_name='serviciocotizacion',
            name='divisaInicial',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='serviciocotizacion',
            name='precioTotalInicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
