# Generated by Django 3.2.3 on 2021-07-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0005_auto_20210708_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciocotizacion',
            name='divisaFinalal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='serviciocotizacion',
            name='divisaInicial',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
