# Generated by Django 3.2.3 on 2021-07-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0006_auto_20210708_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviciocotizacion',
            old_name='divisaFinalal',
            new_name='divisaFinal',
        ),
    ]
