# Generated by Django 3.2.3 on 2021-07-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0007_rename_divisafinalal_serviciocotizacion_divisafinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciocotizacion',
            name='rechazo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
