# Generated by Django 3.2.3 on 2021-07-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0009_alter_serviciocotizacion_rechazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactocotizacion',
            name='idVenta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='serviciocotizacion',
            name='idVenta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='serviciosagregadoscotizacion',
            name='idVenta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
