# Generated by Django 3.2.3 on 2021-07-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0012_alter_serviciosagregadoscotizacion_agregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciocotizacion',
            name='diasTransito',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
