# Generated by Django 3.2.3 on 2021-08-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0013_serviciocotizacion_diastransito'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciosagregadoscotizacion',
            name='divisa',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
