# Generated by Django 3.2.3 on 2021-08-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0015_auto_20210806_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciocotizacion',
            name='estibable',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='serviciocotizacion',
            name='nametipoUnidad',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
