# Generated by Django 3.2 on 2022-12-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0018_auto_20221229_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviciocotizacion',
            old_name='idcotizacion',
            new_name='folioCotizacion',
        ),
    ]
