# Generated by Django 3.2 on 2022-12-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0019_rename_idcotizacion_serviciocotizacion_foliocotizacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consecutivo',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='folioCotizacion',
        ),
    ]
