# Generated by Django 3.2 on 2022-12-29 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0024_consecutivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consecutivo',
        ),
    ]
