# Generated by Django 3.2 on 2022-12-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0028_consecutivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consecutivo',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
