# Generated by Django 3.2 on 2022-12-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0029_alter_consecutivo_numero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consecutivo',
        ),
    ]
