# Generated by Django 3.2 on 2022-12-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0030_delete_consecutivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consecutivo',
            fields=[
                ('idConsecutivo', models.IntegerField(blank=True, default=0, primary_key=True, serialize=False)),
                ('numero', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
