# Generated by Django 3.2 on 2022-12-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0032_alter_consecutivo_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consecutivo',
            name='idConsecutivo',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
