# Generated by Django 3.2 on 2022-12-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0033_auto_20221229_1418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consecutivo',
        ),
    ]
