# Generated by Django 3.2 on 2022-12-29 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0035_consecutivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consecutivo',
            name='idConsecutivo',
        ),
    ]
