# Generated by Django 3.2 on 2023-01-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0037_auto_20221229_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciocotizacion',
            name='folioConsecutivo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
