# Generated by Django 3.2 on 2023-01-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0039_auto_20230105_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='clasificacion',
        ),
        migrations.AddField(
            model_name='serviciocotizacion',
            name='idclasificacion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
