# Generated by Django 3.2 on 2023-01-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0041_alter_serviciocotizacion_idclasificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactocotizacion',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
