# Generated by Django 3.2 on 2023-01-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0042_alter_contactocotizacion_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciocotizacion',
            name='tipoServicio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
