# Generated by Django 3.2 on 2023-01-31 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0044_auto_20230116_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciocotizacion',
            name='zona',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
