# Generated by Django 3.2 on 2023-02-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0046_auto_20230210_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciosagregadoscotizacion',
            name='cambiosConsecutivo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
