# Generated by Django 3.2 on 2023-03-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0048_auto_20230216_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciosagregadoscotizacion',
            name='cambiosConsecutivo',
        ),
        migrations.AddField(
            model_name='serviciocotizacion',
            name='cambiosConsecutivo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='serviciocotizacion',
            name='primerCambio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
