# Generated by Django 3.2 on 2023-03-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0049_auto_20230301_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciocotizacion',
            name='usuarioGenera',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
