# Generated by Django 3.2 on 2023-04-02 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_zonashijos_colonia'),
        ('cotizaciones', '0050_serviciocotizacion_usuariogenera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifas',
            fields=[
                ('idTarifa', models.AutoField(primary_key=True, serialize=False)),
                ('tarifaKilometro', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.IntegerField(blank=True, default=0, null=True)),
                ('idTarifasDestino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idTarifaDestino', to='customer.zonashijos')),
                ('idTarifasOrigen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idTarifaOrigen', to='customer.zonashijos')),
            ],
        ),
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('idRuta', models.AutoField(primary_key=True, serialize=False)),
                ('kilometraje', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('porcZonaNoCom', models.IntegerField(blank=True, default=0, null=True)),
                ('porcZonaPelig', models.IntegerField(blank=True, default=0, null=True)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
                ('idrutasDestino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idZonasHijoDestino', to='customer.zonashijos')),
                ('idrutasOrigen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idZonasHijoOrigen', to='customer.zonashijos')),
            ],
        ),
    ]
