# Generated by Django 3.2 on 2023-04-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0051_rutas_tarifas'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutas',
            name='zona',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
