# Generated by Django 3.2 on 2023-04-02 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0052_rutas_zona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutas',
            name='zona',
        ),
    ]
