# Generated by Django 3.2 on 2023-04-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0053_remove_rutas_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciosagregadoscotizacion',
            name='kilometraje',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serviciosagregadoscotizacion',
            name='porcIva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serviciosagregadoscotizacion',
            name='porcNComercial',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serviciosagregadoscotizacion',
            name='porcSobrepeso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serviciosagregadoscotizacion',
            name='porcSusceptible',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serviciosagregadoscotizacion',
            name='porcZPeligrosa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serviciosagregadoscotizacion',
            name='tarifaKilometraje',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serviciosagregadoscotizacion',
            name='totalServicio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='serviciosagregadoscotizacion',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
