# Generated by Django 3.2 on 2023-04-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0056_rutas_tiempoestimado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifas',
            name='tipoUnidad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
