# Generated by Django 3.2 on 2023-04-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0057_tarifas_tipounidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciosagregadoscotizacion',
            name='aumento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviciosagregadoscotizacion',
            name='porcAumento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
