# Generated by Django 3.2 on 2023-04-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0058_auto_20230406_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciocotizacion',
            name='alto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='serviciocotizacion',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='serviciocotizacion',
            name='largo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='serviciocotizacion',
            name='unidadPeso',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
