# Generated by Django 3.2 on 2023-04-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0059_auto_20230427_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciocotizacion',
            name='valorDeclaradoMerc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
