# Generated by Django 3.2 on 2023-06-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0060_serviciocotizacion_valordeclaradomerc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifario',
            fields=[
                ('idTarifa', models.AutoField(primary_key=True, serialize=False)),
                ('origen', models.CharField(blank=True, max_length=30, null=True)),
                ('destino', models.CharField(blank=True, max_length=15, null=True)),
                ('factor_conversion', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('recoleccion_tres_y_media', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('recoleccion_rabon', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('recoleccion_torton', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('flete_nacional', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('entrega_puerto_nissan', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('entrega_puerto_tres_y_media', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('entrega_rabon', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('entrega_torton', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('usuarioAlta', models.CharField(max_length=150, null=True)),
                ('usuarioModifica', models.CharField(max_length=150, null=True)),
                ('dateEdita', models.DateTimeField(null=True)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ('idTarifa',),
            },
        ),
    ]
