# Generated by Django 3.2 on 2023-07-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0062_mercancias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mercancias',
            options={},
        ),
        migrations.RemoveField(
            model_name='mercancias',
            name='estatus',
        ),
        migrations.AddField(
            model_name='mercancias',
            name='precioVolumen',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mercancias',
            name='upeso',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
