# Generated by Django 3.2 on 2023-07-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0063_auto_20230706_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercancias',
            name='umedi',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
