# Generated by Django 3.2 on 2023-07-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0064_mercancias_umedi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercancias',
            name='embalaje',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
