# Generated by Django 3.2 on 2023-07-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0065_alter_mercancias_embalaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercancias',
            name='usuarioAlta',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
