# Generated by Django 3.2 on 2023-07-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0066_mercancias_usuarioalta'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciocotizacion',
            name='calleDestino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviciocotizacion',
            name='calleOrigen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviciocotizacion',
            name='numExtDestino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviciocotizacion',
            name='numExtOrigen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviciocotizacion',
            name='numIntDestino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviciocotizacion',
            name='numIntOrigen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
