# Generated by Django 3.2 on 2023-07-27 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0067_auto_20230713_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('idPlan', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePlan', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('divisa', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('incon', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('despripcion', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('elegido', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('idCotizacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idCotizacion_planes', to='cotizaciones.serviciocotizacion')),
            ],
        ),
    ]
