# Generated by Django 3.2 on 2023-07-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0068_planes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planes',
            old_name='nombrePlan',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='planes',
            old_name='despripcion',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='divisa',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='elegido',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='incon',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='precio',
        ),
        migrations.AddField(
            model_name='planes',
            name='bandwidth',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='planes',
            name='domain',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='planes',
            name='ribbon',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='planes',
            name='seleccionado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planes',
            name='services',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='planes',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='planes',
            name='user',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
