# Generated by Django 3.2 on 2023-07-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0069_auto_20230727_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
