# Generated by Django 3.2 on 2023-07-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0070_planes_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes',
            name='ribbon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
