# Generated by Django 3.2 on 2023-08-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0071_alter_planes_ribbon'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciocotizacion',
            name='almacenOcurreDestino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviciocotizacion',
            name='almacenOcurreOrigen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
