# Generated by Django 3.2 on 2023-08-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0072_auto_20230731_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutasFTL',
            fields=[
                ('idRuta', models.AutoField(primary_key=True, serialize=False)),
                ('kilometraje', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('porcZonaNoCom', models.IntegerField(blank=True, default=0, null=True)),
                ('porcZonaPelig', models.IntegerField(blank=True, default=0, null=True)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
                ('tiempoEstimado', models.CharField(blank=True, max_length=80, null=True)),
                ('paisOrigen', models.CharField(blank=True, max_length=100, null=True)),
                ('cpOrigen', models.CharField(blank=True, max_length=10, null=True)),
                ('estadoOrigen', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudadOrigen', models.CharField(blank=True, max_length=100, null=True)),
                ('paisDestino', models.CharField(blank=True, max_length=100, null=True)),
                ('cpDestino', models.CharField(blank=True, max_length=10, null=True)),
                ('estadoDestino', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudadDestino', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
