# Generated by Django 3.2 on 2023-09-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0073_rutasftl'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifario',
            name='aplica',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
