# Generated by Django 3.2 on 2023-10-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0074_tarifario_aplica'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifasFTL',
            fields=[
                ('id_Tarifa', models.AutoField(primary_key=True, serialize=False)),
                ('tarifa_kilometro', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('estatus', models.IntegerField(blank=True, default=0, null=True)),
                ('pais_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('cp_origen', models.CharField(blank=True, max_length=10, null=True)),
                ('pais_destino', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_destino', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad_destino', models.CharField(blank=True, max_length=100, null=True)),
                ('cp_destino', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_unidad', models.IntegerField(blank=True, default=0, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
