# Generated by Django 3.2 on 2023-10-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0075_tarifasftl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rutas',
            old_name='dateCreate',
            new_name='date_create',
        ),
        migrations.RenameField(
            model_name='rutas',
            old_name='idRuta',
            new_name='id_ruta',
        ),
        migrations.RenameField(
            model_name='rutas',
            old_name='porcZonaNoCom',
            new_name='porc_zona_no_com',
        ),
        migrations.RenameField(
            model_name='rutas',
            old_name='porcZonaPelig',
            new_name='porc_zona_pelig',
        ),
        migrations.RenameField(
            model_name='rutas',
            old_name='tiempoEstimado',
            new_name='tiempo_estimado',
        ),
        migrations.RemoveField(
            model_name='rutas',
            name='idrutasDestino',
        ),
        migrations.RemoveField(
            model_name='rutas',
            name='idrutasOrigen',
        ),
        migrations.AddField(
            model_name='rutas',
            name='ciudad_destino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rutas',
            name='ciudad_origen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rutas',
            name='cp_destino',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rutas',
            name='cp_origen',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rutas',
            name='estado_destino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rutas',
            name='estado_origen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rutas',
            name='modalidad',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='rutas',
            name='pais_destino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rutas',
            name='pais_origen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
