# Generated by Django 3.2 on 2023-10-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0076_auto_20231017_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifario',
            name='entrega_trailer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tarifario',
            name='recoleccion_nissan',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tarifario',
            name='recoleccion_trailer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tarifario',
            name='destino',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tarifario',
            name='origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
