# Generated by Django 3.2 on 2024-11-05 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0077_auto_20231026_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarifario',
            old_name='destino',
            new_name='ciudad_destino',
        ),
        migrations.RenameField(
            model_name='tarifario',
            old_name='origen',
            new_name='ciudad_origen',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='almacenOcurreDestino',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='almacenOcurreOrigen',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='alto',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='ancho',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='calleDestino',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='calleOrigen',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='ciudadDestino',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='ciudadOrigen',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='classHaz',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='cpDestino',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='cpOrigen',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='descrip',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='embalaje',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='estadoDestino',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='estadoOrigen',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='gradosRef',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='idclasificacion',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='idestadoDestino',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='idestadoOrigen',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='idpaisDestino',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='idpaisOrigen',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='largo',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='numExtDestino',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='numExtOrigen',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='numIntDestino',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='numIntOrigen',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='paisDestino',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='paisOrigen',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='pesoTotal',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='tipoUnidadRef',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='unHaz',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='unidadMedida',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='unidadPeso',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='valorDeclaradoMerc',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='volumen',
        ),
        migrations.RemoveField(
            model_name='serviciocotizacion',
            name='zona',
        ),
        migrations.AddField(
            model_name='mercancias',
            name='clasificacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mercancias',
            name='classP',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mercancias',
            name='descripRef',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mercancias',
            name='descripcion_mercancia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mercancias',
            name='es_peligrosa',
            field=models.BooleanField(blank=True, default=False, max_length=7),
        ),
        migrations.AddField(
            model_name='mercancias',
            name='es_refrigerada',
            field=models.BooleanField(blank=True, default=False, max_length=7),
        ),
        migrations.AddField(
            model_name='mercancias',
            name='grados',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mercancias',
            name='idclasificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mercancias',
            name='mercancia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mercancias',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mercancias',
            name='ruta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mercancias',
            name='un',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serviciocotizacion',
            name='id_unidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviciocotizacion',
            name='servicio_stops',
            field=models.BooleanField(blank=True, default=False, max_length=7),
        ),
        migrations.AddField(
            model_name='tarifario',
            name='estado_destino',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tarifario',
            name='estado_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tarifario',
            name='pais_destino',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tarifario',
            name='pais_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serviciocotizacion',
            name='folioConsecutivo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='DireccionCotizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paisOrigen', models.CharField(blank=True, max_length=100, null=True)),
                ('idpaisOrigen', models.IntegerField(blank=True, default=0, null=True)),
                ('cpOrigen', models.CharField(blank=True, max_length=10, null=True)),
                ('estadoOrigen', models.CharField(blank=True, max_length=100, null=True)),
                ('idestadoOrigen', models.IntegerField(blank=True, default=0, null=True)),
                ('ciudadOrigen', models.CharField(blank=True, max_length=100, null=True)),
                ('coloniaOrigen', models.CharField(blank=True, max_length=100, null=True)),
                ('calleOrigen', models.CharField(blank=True, max_length=100, null=True)),
                ('numExtOrigen', models.CharField(blank=True, max_length=100, null=True)),
                ('numIntOrigen', models.CharField(blank=True, max_length=100, null=True)),
                ('almacenOcurreOrigen', models.CharField(blank=True, max_length=100, null=True)),
                ('paisDestino', models.CharField(blank=True, max_length=100, null=True)),
                ('idpaisDestino', models.IntegerField(blank=True, default=0, null=True)),
                ('cpDestino', models.CharField(blank=True, max_length=10, null=True)),
                ('estadoDestino', models.CharField(blank=True, max_length=100, null=True)),
                ('idestadoDestino', models.IntegerField(blank=True, default=0, null=True)),
                ('ciudadDestino', models.CharField(blank=True, max_length=100, null=True)),
                ('coloniaDestino', models.CharField(blank=True, max_length=100, null=True)),
                ('calleDestino', models.CharField(blank=True, max_length=100, null=True)),
                ('numExtDestino', models.CharField(blank=True, max_length=100, null=True)),
                ('numIntDestino', models.CharField(blank=True, max_length=100, null=True)),
                ('almacenOcurreDestino', models.CharField(blank=True, max_length=100, null=True)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
                ('usuarioGenera', models.CharField(blank=True, max_length=150, null=True)),
                ('km', models.CharField(blank=True, max_length=50, null=True)),
                ('zona', models.CharField(blank=True, max_length=50, null=True)),
                ('identificador', models.CharField(blank=True, max_length=200, null=True)),
                ('idcotizacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idCotizacion_direcciones', to='cotizaciones.serviciocotizacion')),
            ],
        ),
    ]
