# Generated by Django 3.2.3 on 2021-07-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('lada', models.CharField(blank=True, max_length=6, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('cp', models.CharField(blank=True, max_length=12, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('colonia', models.CharField(blank=True, max_length=50, null=True)),
                ('calle', models.CharField(blank=True, max_length=90, null=True)),
                ('noInterior', models.CharField(blank=True, max_length=20, null=True)),
                ('noExterior', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('tipoEmpresa', models.CharField(blank=True, max_length=20, null=True)),
                ('rfc', models.CharField(max_length=20, null=True)),
                ('taxID', models.CharField(blank=True, max_length=20, null=True)),
                ('usoCfdi', models.CharField(blank=True, max_length=30, null=True)),
                ('formaPago', models.CharField(blank=True, max_length=30, null=True)),
                ('metodoPago', models.CharField(blank=True, max_length=30, null=True)),
                ('estatus', models.CharField(blank=True, max_length=10, null=True)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
