# Generated by Django 3.2.3 on 2021-07-14 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_datacomplementary_customer'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProvider', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=60)),
                ('lada', models.CharField(max_length=6, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('estatus', models.IntegerField()),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RutasProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProvider', models.IntegerField()),
                ('cpOrigen', models.CharField(max_length=20)),
                ('ciudadOrigen', models.CharField(max_length=200)),
                ('cpDestino', models.CharField(max_length=20)),
                ('ciudadDestino', models.CharField(max_length=200)),
                ('estatus', models.IntegerField()),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
                ('estadoDestino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pestadoDestino_id', to='customer.estates')),
                ('estadoOrigen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pestadoOrigen_id', to='customer.estates')),
                ('paisDestino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ppaisDestino_id', to='customer.country')),
                ('paisOrigen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ppaisOrigen_id', to='customer.country')),
            ],
            options={
                'ordering': ('paisOrigen',),
            },
        ),
        migrations.CreateModel(
            name='FilesProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('ruta', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('statuspdf', models.IntegerField(blank=True, null=True)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
                ('idProvider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider1', to='proveedores.proveedor')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DataComplementary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbersemployes', models.CharField(blank=True, max_length=200, null=True)),
                ('business', models.CharField(blank=True, max_length=200, null=True)),
                ('specification', models.CharField(blank=True, max_length=100, null=True)),
                ('conditions', models.CharField(blank=True, max_length=100, null=True)),
                ('paydaysweeks', models.CharField(blank=True, max_length=100, null=True)),
                ('generalnotesweeks', models.CharField(blank=True, max_length=100, null=True)),
                ('paydaysdate', models.CharField(blank=True, max_length=100, null=True)),
                ('generalnotesdate', models.CharField(blank=True, max_length=100, null=True)),
                ('creditdays', models.CharField(blank=True, max_length=100, null=True)),
                ('credit', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('idProvider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider2', to='proveedores.proveedor')),
            ],
        ),
    ]
