# Generated by Django 3.2.3 on 2021-07-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_alter_contactop_idprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactop',
            name='idProvider',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
